services:
  postgres:
    image: postgres:17-alpine
    container_name: school-postgres
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '685974'
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - school-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: school-redis
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - school-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: school-backend
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: school_db
      DB_USER: postgres
      DB_PASSWORD: '685974'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORS_ORIGIN: '*'
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - school-network
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    container_name: school-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - school-network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  school-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: 
